name: Workflow para gerar ASCII Artwork
on: push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:

       - name: Faz o checkout do repo
         uses: actions/checkout@v6

       - name: Executing Shell Script
         run: bash shell.sh

       - name: Lista os arquivos do reposit√≥rio
         run: ls