name: Meu primeiro workflow
on: push
jobs:
    primeiro_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
            - name: MÃºltiplos comandos
              run: |
                echo "Meu primeiro workflow"
                ls -ltra
                cat /etc/passwd
            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover... I am a DRAGON!!" >> dragon.txt
#            #- name: Listar arquivos
#            #  run: ls 
#            #- name: Ler um arquivo
#            #  run: cat /etc/passwd