name: Workflow Filters and Activities
on:
  workflow_dispatch:
  push:
    #branches-ignore:
    #  - feature/*
    #  - test/**
    branches:
      - main
      - '!feature/*' # qualquer branch que não comece com esse nome
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - name: Fazendo a execução
         run: echo Esse workflow/job/step foi disparado pelo evento ${{ github.event_name }}